name: pull-request
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  code:
    uses: cyberuni/.github/.github/workflows/pnpm-verify.yml@main
    with:
      os: '["ubuntu-latest"]'
      skip-codecov: true
  codecov:
    uses: cyberuni/.github/.github/workflows/pnpm-codecov.yml@main
    with:
      files: ./packages/resolve.imports/coverage/lcov.info
      flags: resolve.imports
