name: release
on:
  push:
    branches: [main]

jobs:
  code:
    uses: cyberuni/.github/.github/workflows/pnpm-verify.yml@main
    with:
      os: '["ubuntu-latest"]'
      skip-codecov: true
  codecov:
    uses: cyberuni/.github/.github/workflows/pnpm-codecov.yml@main
    with:
      files: ./packages/resolve.imports/coverage/lcov.info
      flags: resolve.imports

  release:
    uses: cyberuni/.github/.github/workflows/pnpm-release-changeset.yml@main
    needs: code
    secrets: inherit
